### ISSUE TITLE
Project License?

### ISSUE THREAD

**Issue by aschrijver** [villagescc/villagesio2.0#111]
I found this (very interesting) project via Codeberg Switching Software project, where it was also [mentioned that there is no license](https://codeberg.org/swiso/website/issues/141#issuecomment-72219). This effectively makes this proprietary software.

It was mentioned that previously there _was_ a license. Do you intend to add one?

**Comment by allinfinite** [comment]
It’s listed on our readme GNU GENERAL PUBLIC LICENSE

**Comment by aschrijver** [comment]
Oh, ha ha. It was too obvious in all-caps, so I overlooked it. Need :coffee: 

Isn't it best to provide a LICENSE file (so GH parses it in the sidebar, and it is clearer in forks/clones, etc.)? Also to state which version of GPL. Your other project is AGPL-3.0 I saw.
