### ISSUE TITLE
www.villages.cc is not redirecting

### ISSUE THREAD

**Issue by allinfinite** [villagescc/villagesio2.0#84]
not sure if this needs to be done on aws or on the registrar

**Comment by themusicgod1** [comment]
www.villages.cc isn't but villages.cc is.

**Comment by rfugger** [comment]
I have no control over this.  The domain is pointed to your AWS name servers.  Beyond that it's up to you guys :)

**Comment by themusicgod1** [comment]
https://m.anyhu.gs/objects/2f79e0de-10b7-4f7c-adf8-2fec44e14dcd reporting redirect problems from https://villages.cc:443
